#!/bin/bash

~/.cargo/bin/vocage -1 ~/japan/words.tsv
~/.cargo/bin/vocage -1 ~/japan/kanji.tsv
~/.cargo/bin/vocage -1 ~/japan/words2.tsv

sed 's/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]/01:00:00/g' -i ~/japan/words.tsv
sed 's/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]/01:00:00/g' -i ~/japan/words2.tsv
sed 's/[0-9][0-9]:[0-9][0-9]:[0-9][0-9]/01:00:00/g' -i ~/japan/kanji.tsv
